#!/bin/bash
CLASSPATH=$CLASSPATH:../lib/guava-18.0.jar:../lib/pokersource.jar:../lib/jopt-simple-5.0.2.jar:.
javac -cp $CLASSPATH \
    ./sfh/GameState.java \
    ./sfh/SfhRunner.java \
    ./sfh/Strategy.java \
    ./sfh/games/resistance/ResistanceEvilStrategy.java \
    ./sfh/games/resistance/ResistanceGameState.java \
    ./sfh/games/resistance/ResistanceGoodStrategy.java \
    ./sfh/games/resistance/AbstractResistanceStrategy.java \
    ./sfh/games/hubadugi/HuBadugiGameState.java \
    ./sfh/badugi/CardSet.java &&
java -cp $CLASSPATH sfh/SfhRunner $*
