#!/bin/bash

#Usage: time ./run-sfh --game=badugi --iterations=1
CLASSPATH=$CLASSPATH:../lib/guava-23.0.jar:../lib/pokersource.jar:../lib/jopt-simple-5.0.2.jar:.
javac -cp $CLASSPATH \
    ./sfh/GameState.java \
    ./sfh/SfhRunner.java \
    ./sfh/Strategy.java \
    ./sfh/games/resistance/ResistanceEvilStrategy.java \
    ./sfh/games/resistance/ResistanceGameState.java \
    ./sfh/games/resistance/ResistanceGoodStrategy.java \
    ./sfh/games/resistance/AbstractResistanceStrategy.java \
    ./sfh/games/hubadugi/HuBadugiGameState.java \
    ./sfh/cards/CardSet.java \
    ./sfh/cards/Deck.java &&
java -cp $CLASSPATH sfh/SfhRunner $*
